// Generated by Wrangler by running `wrangler types`

interface Env {
	SECRET: string;
	IV_SECRET: string;
	// Durable Object binding for request coalescing
	DOWNLOAD_COALESCER: DurableObjectNamespace;
}
